// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "unicomer-test/internal/holiday/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// HolidayFindQuery is an autogenerated mock type for the HolidayFindQuery type
type HolidayFindQuery struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, holidayType, date
func (_m *HolidayFindQuery) Execute(ctx context.Context, holidayType string, date time.Time) ([]domain.Holiday, error) {
	ret := _m.Called(ctx, holidayType, date)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []domain.Holiday
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]domain.Holiday, error)); ok {
		return rf(ctx, holidayType, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []domain.Holiday); ok {
		r0 = rf(ctx, holidayType, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Holiday)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, holidayType, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHolidayFindQuery creates a new instance of HolidayFindQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHolidayFindQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *HolidayFindQuery {
	mock := &HolidayFindQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
